apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .chart.Version }}"
    component: "{{ template "fullname" . }}"
    run: {{ template "fullname" . }}
  annotations:
    "helm.sh/created": {{ .Release.Time.Seconds | quote }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ template "fullname" . }}"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .chart.Version }}"
        component: "{{ template "fullname" . }}"
        run: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy}}"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
        ports:
        - containerPort: 5000
          name: http
