apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{template "fullname" . }}-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: workshop.com
    http:
      paths:
      - path: /k8s
        backend:
          serviceName: {{template "fullname" . }}
          servicePort: 5000
