apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}"
  annotations:
    "helm.sh/created": {{ .Release.Time.Seconds | quote }}
    "kong/request-path": {{ .Values.BasePath | quote }}
    "kong/preserve-host": "true"
    "kong/strip-request-path": "false"
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: web
      targetPort: 5000
  selector:
    component: "{{ template "fullname" . }}"
  type: {{ .Values.service.type | quote }}
